### ISSUE TITLE
Adding or copying a translation (of a page) ends with a white page (copy is successful, though)

### ISSUE THREAD

**Issue by schnitzler** [papayaCMS/papayacms-core#27]
When adding or copying a translation (of a page), I get a white page (copy is successful, though).

See screenshot to see where we are.

I _think_ the following log entry is related to the issue:

Uncaught exception 'OutOfBoundsException' with message 'Property/Index "lng_id" is not defined for item class "PapayaContentLanguage".' in {PAPAYA_INCLUDE_PATH}/system/Papaya/Object/Item.php:196

**Backtrace**

PapayaObjectItem->_prepareName() {PAPAYA_INCLUDE_PATH}/system/Papaya/Object/Item.php:117
PapayaObjectItem->__get() {PAPAYA_INCLUDE_PATH}/system/Papaya/Database/Record/Lazy.php:123
PapayaDatabaseRecordLazy->__get() {PAPAYA_INCLUDE_PATH}/system/Papaya/Object/Item.php:160
PapayaObjectItem->offsetGet() {PAPAYA_INCLUDE_PATH}/system/base_topic.php:660
base_topic->loadMetaData() {PAPAYA_INCLUDE_PATH}/system/base_topic_edit.php:3313
base_topic_edit->getTopicInformation() {PAPAYA_INCLUDE_PATH}/system/base_topic_edit.php:3558
base_topic_edit->getInformation() {PAPAYA_INCLUDE_PATH}/system/base_topic_edit.php:709
base_topic_edit->execute() /var/www/papaya.2016-04-20.13-54-v3.0.15.60e7b37/htdocs/papaya/topic.php:34

(using papaya 5.6)

![papaya-translation](https://cloud.githubusercontent.com/assets/7204077/15332919/d7e95262-1c67-11e6-8566-7a34fbc0cd61.png)

**Comment by ThomasWeinert** [comment]
Fixed with https://github.com/papayaCMS/papayacms-core/commit/fee73840584c1f901281007cebc42b278ad2a4d7#diff-0f8495cb7dc1e1b14e33e0ba37333a3e
